apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: composition
spec:
  resources:
    - name: aks-cluster
      base:
        apiVersion: containerservice.azure.upbound.io/v1beta1
        kind: KubernetesCluster
        metadata:
          labels:
            testing.upbound.io/cluster-name: aks
          name: aks
        spec:
          forProvider:
            apiServerAccessProfile:
              - authorizedIpRanges:
                  - 192.168.1.0/24
            defaultNodePool:
              - name: default
                nodeCount: 1
                vmSize: Standard_D2_v2
            dnsPrefix: aks1
            identity:
              - type: SystemAssigned
            location: East US
            resourceGroupName: test1234
            tags:
              Environment: Production
          writeConnectionSecretToRef:
            namespace: crossplane-system
      patches:
      - type: FromCompositeFieldPath
        fromFieldPath: "spec.instance_type"
        toFieldPath: "spec.forProvider.defaultNodePool[0].vmSize"
      - type: FromCompositeFieldPath
        fromFieldPath: "spec.count"
        toFieldPath: "spec.forProvider.defaultNodePool[0].nodeCount"
      - type: FromCompositeFieldPath
        fromFieldPath: "spec.writeConnectionSecretToRef.namespace"
        toFieldPath: "spec.writeConnectionSecretToRef.namespace"
      - type: FromCompositeFieldPath
        fromFieldPath: "metadata.uid"
        toFieldPath: "spec.writeConnectionSecretToRef.name"
        transforms:
          - type: string
            string:
              fmt: "%s-akscluster"
      connectionDetails:
        - fromConnectionSecretKey: kubeconfig
          name: kubeconfig
          type: FromConnectionSecretKey

    - name: providerConfigHelm
      base:
        apiVersion: helm.crossplane.io/v1beta1
        kind: ProviderConfig
        spec:
          credentials:
            source: Secret
            secretRef:
              namespace: crossplane-system
              key: kubeconfig
      patches:
      - type: FromCompositeFieldPath
        fromFieldPath: "spec.writeConnectionSecretToRef.namespace"
        toFieldPath: "spec.credentials.secretRef.namespace"
      - type: FromCompositeFieldPath
        fromFieldPath: "metadata.uid"
        toFieldPath: "spec.credentials.secretRef.name"
        transforms:
          - type: string
            string:
              fmt: "%s-akscluster"

    - name: virtual-network
      base:
        apiVersion: network.azure.upbound.io/v1beta1
        kind: VirtualNetwork
        metadata:
          name: crossplane-network
        spec:
          forProvider:
            addressSpace:
              - 10.2.0.0/16
            location: East US
            resourceGroupName: test1234
      patches:
      - type: FromCompositeFieldPath
        fromFieldPath: "spec.location"
        toFieldPath: "spec.forProvider.location"
    - name: subnet
      base:
        apiVersion: network.azure.upbound.io/v1beta1
        kind: Subnet
        metadata:
          name: crossplane-subnet
        spec:
          forProvider:
            addressPrefixes:
              - 10.2.0.0/24
            resourceGroupNameRef:
              name: test1234
            virtualNetworkNameSelector:
              matchControllerRef: true
    - name: nginx
      base:
        apiVersion: helm.crossplane.io/v1beta1
        kind: Release
        metadata:
          name: nginx-release
        spec:
          forProvider:
            chart:
              name: nginx
              repository: "https://charts.bitnami.com/bitnami"
              version: "13.0.0"  
            namespace: default
            values:
              service:
                type: LoadBalancer
          providerConfigRef:
            name: providerConfigHelm

  compositeTypeRef:
    apiVersion: azure.platform.io/v1alpha1
    kind: xCluster
