apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: composition
spec:
  resources:
    - base:
        apiVersion: containerservice.azure.upbound.io/v1beta1
        kind: KubernetesCluster
        metadata:
          labels:
            testing.upbound.io/cluster-name: aks
          name: aks
        spec:
          forProvider:
            apiServerAccessProfile:
              - authorizedIpRanges:
                  - 192.168.1.0/24
            defaultNodePool:
              - name: default
                nodeCount: 1
                vmSize: Standard_D2_v2
            dnsPrefix: aks1
            identity:
              - type: SystemAssigned
            location: East US
            resourceGroupName: test1234
            tags:
              Environment: Production
      patches:
      - type: FromCompositeFieldPath
        fromFieldPath: "spec.instance_type"
        toFieldPath: "spec.forProvider.defaultNodePool[0].vmSize"
      - type: FromCompositeFieldPath
        fromFieldPath: "spec.count"
        toFieldPath: "spec.forProvider.defaultNodePool[0].nodeCount"
  compositeTypeRef:
    apiVersion: azure.platform.io/v1alpha1
    kind: xCluster

